name: capitals
description: A fancy flutter app example.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  tcard: ^1.3.5
  palette_generator: ^0.3.0
  wave: ^0.2.0

  get_it: ^7.2.0
  injectable: ^1.4.1
  provider: ^6.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.6
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/pictures.json